import * as d3 from 'https://cdn.jsdelivr.net/npm/d3@7.9.0/+esm';

// --------------------------- Load & parse CSV ---------------------------
async function loadData() {
  // loc.csv is generated by elocuent
  const data = await d3.csv('loc.csv', (row) => ({
    ...row,
    line: +row.line,
    depth: +row.depth,
    length: +row.length,
    date: new Date(row.date + 'T00:00' + row.timezone),
    datetime: new Date(row.datetime),
  }));
  return data;
}

// --------------------------- Commit extraction ---------------------------
function processCommits(data, repoUrl) {
  return d3
    .groups(data, (d) => d.commit) // [commitId, lines[]]
    .map(([commit, lines]) => {
      const first = lines[0];
      const { author, date, time, timezone, datetime } = first;
      const ret = {
        id: commit,
        url: `${repoUrl.replace(/\/$/, '')}/commit/${commit}`,
        author,
        date,
        time,
        timezone,
        datetime,
        hourFrac: datetime.getHours() + datetime.getMinutes() / 60,
        totalLines: lines.length,
      };
      Object.defineProperty(ret, 'lines', {
        value: lines,
        configurable: false,
        enumerable: false,  // hide in console listing
        writable: false,
      });
      return ret;
    });
}

// --------------------------- Summary stats ---------------------------
function renderCommitInfo(data, commits) {
  const dl = d3.select('#stats').append('dl').attr('class', 'stats');

  const add = (label, value) => {
    dl.append('dt').html(label);
    dl.append('dd').text(value);
  };

  add('COMMITS', commits.length);
  add('FILES', d3.groups(data, (d) => d.file).length);
  add('TOTAL <abbr title="Lines of code">LOC</abbr>', data.length);

  const longestLine = d3.greatest(data, (d) => d.length);
  add('LONGEST LINE', longestLine?.length ?? 0);

  const maxLinesPerFile = d3.rollups(
    data,
    v => d3.max(v, (r) => r.line),
    d => d.file
  );
  add('MAX LINES', d3.max(maxLinesPerFile, d => d[1]) ?? 0);

  add('MAX DEPTH', d3.max(data, (d) => d.depth) ?? 0);
}

// --------------------------- Tooltip helpers ---------------------------
function renderTooltipContent(commit) {
  if (!commit) return;
  const link = document.getElementById('commit-link');
  const date = document.getElementById('commit-date');
  const time = document.getElementById('commit-time');
  const author = document.getElementById('commit-author');
  const lines = document.getElementById('commit-lines');

  link.href = commit.url;
  link.textContent = commit.id;
  date.textContent = commit.datetime?.toLocaleString('en', { dateStyle: 'full' });
  time.textContent = commit.datetime?.toLocaleTimeString('en', { hour: '2-digit', minute: '2-digit' });
  author.textContent = commit.author;
  lines.textContent = commit.totalLines;
}
function updateTooltipVisibility(visible) {
  document.getElementById('commit-tooltip').hidden = !visible;
}
function updateTooltipPosition(event) {
  const t = document.getElementById('commit-tooltip');
  const pad = 14;
  t.style.left = `${event.clientX + pad}px`;
  t.style.top  = `${event.clientY + pad}px`;
}

// --------------------------- Scatter plot (Steps 2–4) ---------------------------
function renderScatterPlot(commits) {
  const container = d3.select('#chart');
  container.selectAll('*').remove();

  const width = 1100;
  const height = 620;
  const margin = { top: 10, right: 20, bottom: 40, left: 55 };

  const svg = container.append('svg')
    .attr('viewBox', `0 0 ${width} ${height}`)
    .style('overflow', 'visible');

  const usable = {
    left: margin.left,
    right: width - margin.right,
    top: margin.top,
    bottom: height - margin.bottom,
    width: width - margin.left - margin.right,
    height: height - margin.top - margin.bottom
  };

  const xScale = d3.scaleTime()
    .domain(d3.extent(commits, d => d.datetime))
    .range([usable.left, usable.right])
    .nice();

  const yScale = d3.scaleLinear()
    .domain([0, 24])
    .range([usable.bottom, usable.top]);

  // Gridlines first
  svg.append('g')
    .attr('class', 'gridlines')
    .attr('transform', `translate(${usable.left},0)`)
    .call(d3.axisLeft(yScale).tickFormat('').tickSize(-usable.width));

  // Axes
  const xAxis = d3.axisBottom(xScale);
  const yAxis = d3.axisLeft(yScale).tickFormat(d => String(d % 24).padStart(2,'0') + ':00');

  svg.append('g')
    .attr('transform', `translate(0,${usable.bottom})`)
    .call(xAxis);
  svg.append('g')
    .attr('transform', `translate(${usable.left},0)`)
    .call(yAxis);

  // Dot radius scale (sqrt for area correctness)
  const [minLines, maxLines] = d3.extent(commits, d => d.totalLines);
  const rScale = d3.scaleSqrt().domain([minLines, maxLines]).range([3, 28]);

  // Render dots (large behind, small on top)
  const sorted = d3.sort(commits, d => -d.totalLines);
  const dots = svg.append('g').attr('class', 'dots');

  dots.selectAll('circle')
    .data(sorted)
    .join('circle')
    .attr('cx', d => xScale(d.datetime))
    .attr('cy', d => yScale(d.hourFrac))
    .attr('r', d => rScale(d.totalLines))
    .attr('fill', 'steelblue')
    .style('fill-opacity', 0.7)
    .on('mouseenter', (event, d) => {
      d3.select(event.currentTarget).style('fill-opacity', 1);
      renderTooltipContent(d);
      updateTooltipPosition(event);
      updateTooltipVisibility(true);
    })
    .on('mousemove', updateTooltipPosition)
    .on('mouseleave', (event) => {
      d3.select(event.currentTarget).style('fill-opacity', 0.7);
      updateTooltipVisibility(false);
    });

  // ---------------- Brush (Step 5) ----------------
  const brush = d3.brush()
    .on('start brush end', brushed);

  svg.call(brush);
  // Keep overlay behind dots so hover works
  svg.selectAll('.dots, .overlay ~ *').raise();

  function isCommitSelected(selection, c) {
    if (!selection) return false;
    const [[x0, y0], [x1, y1]] = selection;
    const x = xScale(c.datetime);
    const y = yScale(c.hourFrac);
    return x0 <= x && x <= x1 && y0 <= y && y <= y1;
  }

  function renderSelectionCount(selection) {
    const list = selection ? commits.filter(c => isCommitSelected(selection, c)) : [];
    document.getElementById('selection-count').textContent =
      `${list.length || 'No'} commits selected`;
    return list;
  }

  function renderLanguageBreakdown(selection) {
    const selected = selection ? commits.filter(c => isCommitSelected(selection, c)) : [];
    const useCommits = selected.length ? selected : commits;
    const lines = useCommits.flatMap(c => c.lines);
    const breakdown = d3.rollup(lines, v => v.length, d => d.type); // type: 'js'|'css'|'html'

    const dl = document.getElementById('language-breakdown');
    dl.innerHTML = '';
    const total = lines.length || 1;
    for (const [lang, count] of breakdown) {
      const pct = d3.format('.1~%')(count / total);
      dl.insertAdjacentHTML('beforeend',
        `<dt>${lang.toUpperCase()}</dt><dd>${count} lines (${pct})</dd>`);
    }
  }

  function brushed(event) {
    const selection = event.selection;
    dots.selectAll('circle').classed('selected', d => isCommitSelected(selection, d));
    renderSelectionCount(selection);
    renderLanguageBreakdown(selection);
  }
}

// --------------------------- Boot ---------------------------
// IMPORTANT: change this to your repo URL (used for commit links)
const REPO_URL = 'https://github.com/vis-society/lab-7';

const data = await loadData();
const commits = processCommits(data, REPO_URL);

renderCommitInfo(data, commits);
renderScatterPlot(commits);
